### PR TITLE
Material Design, build updates, and a couple other things

### PR DESCRIPTION
**Pull request by fat-tire**
Found this project a few days ago and when building it made a couple minor changes.

Thanks to BinkyBear for testing.

### CODE REVIEW

**Comment by tux-mind** [comment]
WOW.... I'm looking the changes right now.... awesome.
honestly I'm not very expert with android ( I mean build system, SDK and so on ).

let me test this changes a little.
I need someone that can help me with the UI and the android stuff.
let me known if you want to join the @cSploit/android-devs team :wink:

**Comment by fat-tire** [comment]
I know it's a lot to take in.  Probably should have broken it into several commits, but it was like I just was going to build it-- and after updating the version of gradle and changing the API support and moving the stuff from AndroidManifest.xml to build.gradle accordingly, I also wanted to fix the library/dependency stuff to use gradle's system instead of including the messagepack jars and such at the same time... but then sherlock was a dependency too in lots of files.  Sherlock was a stopgap compatibility solution from a few years ago, but Android now makes a lot more backwards compatible via it's support/appcompat libraries, so I just changed those to use the android built-in support stuff, and THAT required some more structural changes to activities + the menu items, and along the way there were a few crashers I came upon/fixed and some extras like toggle buttons instead of checkmarks for the settings, and of course Android Studio indents the code.. and.. well, the monster commit was the result.  But hopefully, if it works for you, it's a bit cleaner and more up-to-date Android-ish.

Again, nothing was done to add any features or fix things related to functionality (except for including the builder & build date in the About dialog, which was something [I added ](https://github.com/offensive-security/nethunter-app/commit/063d2b7ed1c391ba4b0b9f86a25d87bf54ce09eb) to the Kali [Nethunter app](https://github.com/offensive-security/nethunter-app/tree/fattire) as well)  It's all just a re-factoring to get it to build using the newer tools/libraries, and to bring the UI itself up to date.

Hope it builds/works for you, but if you have questions, stop by #nethunter on freenode irc.

**Comment by tux-mind** [comment]
@xaitax please `rm -rf cSploit/build/*`.

**Comment by xaitax** [comment]
Done and all working smoothly again. :)

**Comment by xaitax** [comment]
Sorry, it doesn't built anymore. Updated SDK and built-tools to latest version but it always runs into the following issue when trying to built the nightly:

<addr>
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':cSploit'.
> Could not resolve all dependencies for configuration ':cSploit:_debugCompile'.
   > Could not find com.android.support:support-v4:22.0.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/22.0.0/support-v4-22.0.0.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/22.0.0/support-v4-22.0.0.jar
         file:/opt/android-sdk-linux/extras/android/m2repository/com/android/support/support-v4/22.0.0/support-v4-22.0.0.pom
         file:/opt/android-sdk-linux/extras/android/m2repository/com/android/support/support-v4/22.0.0/support-v4-22.0.0.jar
         file:/opt/android-sdk-linux/extras/google/m2repository/com/android/support/support-v4/22.0.0/support-v4-22.0.0.pom
         file:/opt/android-sdk-linux/extras/google/m2repository/com/android/support/support-v4/22.0.0/support-v4-22.0.0.jar
     Required by:
         csploit:cSploit:unspecified
   > Could not find com.android.support:appcompat-v7:22.0.0.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/appcompat-v7/22.0.0/appcompat-v7-22.0.0.pom
         https://repo1.maven.org/maven2/com/android/support/appcompat-v7/22.0.0/appcompat-v7-22.0.0.jar
         file:/opt/android-sdk-linux/extras/android/m2repository/com/android/support/appcompat-v7/22.0.0/appcompat-v7-22.0.0.pom
         file:/opt/android-sdk-linux/extras/android/m2repository/com/android/support/appcompat-v7/22.0.0/appcompat-v7-22.0.0.jar
         file:/opt/android-sdk-linux/extras/google/m2repository/com/android/support/appcompat-v7/22.0.0/appcompat-v7-22.0.0.pom
         file:/opt/android-sdk-linux/extras/google/m2repository/com/android/support/appcompat-v7/22.0.0/appcompat-v7-22.0.0.jar
     Required by:
         csploit:cSploit:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
</addr>

**Comment by fat-tire** [comment]
Hmm.  Dunno if this helps...   http://stackoverflow.com/questions/29115223/gradle-build-failed-when-import-support-v4-22-0-0  and/or http://stackoverflow.com/questions/28972903/why-isnt-android-support-library-version-22-available

**Comment by xaitax** [comment]
Didn't help. :/

**Comment by Systemad** [comment]
I had similar problem (if not exact) I  just updated the sdk packages (v22 / 5.1) 
(I'm noob at this so this might be useless "tips")

**Comment by tux-mind** [comment]
is the android support repository installed ?

please open the android sdk manager and update/install "Android Support Repository" and "Android Support Library".

or, from cli:

```sh
./tools/android update sdk -u -a --filter extra-android-support,extra-android-m2repository
```

thanks in advance for your time guys :blush:

**Comment by fat-tire** [comment]
Yeah I still don't see that a new nightly has shown up.  It's a requirement to have the sdk up-to-date since it uses the latest support library stuff, which should be updated with the command tux-mind suggested.  Just run that from the sdk directory.  If you're using Android studio, you can select the SDK manager, make sure "Android Support Repository" and "Android Support Library" is selected, then choose "Install packages" (or "Update packages")  I think it would help to have the Android 5.1.1 (API 22) stuff as well, and obviously the build/platform tools too.

**Comment by xaitax** [comment]
I have all updated. Now it runs into other issues. I am setting up a new server (ordered yesterday) and will migrate everything to it. My current built server:

rootbitch:/home/tools/csploit# uptime
 10:17:54 up 700 days, 6 min,  1 user,  load average: 0.32, 1.40, 1.76

I do/did so many things with it. My bitch slave. Hah. It's time to have a fresh/clean server. Will do everything from scratch. :) Give me a few days and it should be ready and also the cSploit nightly will be back soon. :)

**Pull request merged**
