### PR TITLE
Minor changes of README

### PR DESCRIPTION
**Pull request by RyDroid**

### CODE REVIEW

**Comment by fat-tire** [comment]
I think these some great changes, except I was confused by two:

* Why did you replace the text: "installer.  These are" (which are two sentences) with "installer, these are" (a single run-on sentence separated by a comma)?

* Also, why replace a "rooted device" with "a rooted OS running Android 2.3"?  The OS isn't running another OS-- the device is running the OS.  I think "device" is the righ tword.

Could you reconsider/explain these two changes and maybe fix it up?  If you do, I'll merge this.

Thanks for the great contribution!

**Comment by RyDroid** [comment]
- "If you do not have busybox already, you can get it [...] (note cSploit does not endorse any busybox installer.  These are just two we found)."
  I found strange to end a sentence in parenthesis and did not end the one started in parenthesis.
- The previous sentence said that the device needed to be rooted, but technically it means nothing, it is an OS can give root rights. I fixed the error.

**Comment by fat-tire** [comment]
> The Android OS must have a [BusyBox](http://www.busybox.net/about.html) **full install**, this means with **every** utility installed (not the partial installation). 

The above is a run-on sentence.  It should be something like this:

> The Android OS must have a [BusyBox](http://www.busybox.net/about.html) **full install** with **every** utility installed (not the partial installation). 

I'm not familiar with any prohibition against ending a sentence with a parenthetical, but you can always eliminate it:

> The Android OS must have a [BusyBox](http://www.busybox.net/about.html) **full install** with **every** utility installed-- not just a partial installation.

Also, maybe expand "full install" to "full installation" and shorten a few parts...

> The Android OS must have a [BusyBox](http://www.busybox.net/about.html) **full installation** with **every** utility installed.

As for:

> The previous sentence said that the device needed to be rooted, but technically it means nothing, it is an OS that can give root rights. I fixed the error.

Rooting a device doesn't mean "nothing".  It normally would be understood that root privileges are available to apps.  It's probably better to say

> A **ROOTED** Android 2.3 (Gingerbread) or newer *device*

Although I guess a rooted OS is okay.  I am just objecting to "a rooted OS running Android 2.3", which is weird to my ears since as I mentioned, the rooted OS doesn't run another OS.

Sorry to be super anal about all this... I just don't want to knowingly add a run-on sentence while we're fixing up the text.  Also, while you're fixing that, do you think this has one to many "if any"/"if necessary"s clauses?  Maybe it could be tightened up too (?)

> You should also get your employer (if you work as a programmer) or school, if any, to sign a ?copyright disclaimer? for the program, if necessary.

Thx!

**Comment by RyDroid** [comment]
I updated my commit.

**Comment by tux-mind** [comment]
@fat-tire I'll merge this PR as you confirm it, you have a better knowledge of English than me :wink: 

or feel free to merge it yourself :wink: 

thank you for your help @RyDroid

**Pull request merged**
