### PR TITLE
New portcount design(small changes)

### PR DESCRIPTION
**Pull request by Rubenoo**
I wanted to change the port counter design because i thought that the black background of the port counter didn't fit the csploit profile. you don't have to merge it but i think it would look really nice :)
Before: 
screenshot_2015-10-08-20-58-45
After: 
screenshot_2015-10-08-21-16-15
i hope that you like it :)

### CODE REVIEW

**Comment by Rubenoo** [comment]
I am going to add that if the theme is dark that the background of the portcounter is going to be black to again. tnx to @gain But im currently having some trouble commiting it to my github :(

**Comment by fat-tire** [comment]
Wow, ten commits to change 4 files!  @Rubenoo would it be possible to squash these into a single commit?  It's quite easy-- you just make the changes on your own branch and they will automatically appear here...

Maybe see [here](http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git) or we can help you in IRC....

Nice job btw this is gonna be cool.

**Comment by biomekanika** [comment]
Subtle change but great nonetheless. I like it.

**Comment by tux-mind** [comment]
No problems if @Rubenoo made so much commits :wink:

I'll merge ASAP, I've to check the code anyway.

Thank you for you being eager to learn @Rubenoo :

> my crime is that of curiosity

**Comment by Rubenoo** [comment]
@tux-mind Thank you very much, those words mean alot to me :)
I can maybe squash the commits into 1 commit, but i am having some trouble with github, maybe you can help me some time :)

**Comment by fat-tire** [comment]
Hey Rubenoo I kinda squished all these changes into a single simple [commit](https://github.com/Rubenoo/android/commit/2f20205b97269c8813e30331cd7df6046275a845) in your repository in a new branch, which is [ready for you to submit as a new pull request](https://github.com/cSploit/android/compare/develop...Rubenoo:Rubenoo-New-portcount-design-fattire).  I had considered overwriting this branch but decided to leave it as-is just in case.  If you submit it and it looks good to you, I'll merge it.

**Comment by Rubenoo** [comment]
I've pulled a new pull request with just one commit in stead of 10 commits. You can merge that one if you want

**Pull request closed without merging**
