### PR TITLE
Updated for initial Marshmallow build support

### PR DESCRIPTION
**Pull request by cameronaaron**

### CODE REVIEW

**Comment by fat-tire** [comment]
No not yet--  before Marshmallow is targeted, some work and discussion will need to happen.  By default, Marshmallow will automatically auto-backup 25MB of app data to google drive, which I don't think we want to do- we also have to look at the new runtime permissions model, though it may not be as much of an issue for us since we have root, but we'll probably want to check. We also want to determine the consequences of external storage adoption and remove any hardcoded paths.  There's probably more, that's just off the top of my head.

Switching to M is a bigger deal than just changing the sdk target, and that's why we haven't done it yet... we'll need a more comprehensive review of the consequences of doing it.  Also this PR has conflicts, but we won't be ready to switch to M for a bit I think.

**Comment by cameronaaron** [comment]
Thank you I totally understand! A change like that is a pretty big one I was just trying to get the ball rolling. The backup issue can be resolved simply by adding android:allowBackup="false"> to the build manifest and I don't imagine there being much issue with the new permission model because of root but it might not be a bad idea to allow in the future for users to be able to do some very basic network tools such as ping and traceroute which I don't think would require root just something to think about to open the app up to a wider audience in that case we may have to run regression and be sure the app still functions properly when a user denys/ grants permissions on the app. As for the external storages issue i'm not super familiar with the implementation of that so I can't make any real judgements but my understanding is that it acts as an extension of the data partition and most likely would not cause issues after removing the hard coded paths

**Comment by cameronaaron** [comment]
I am a QA Engineer so let me know if there is any way I can assist you in this project. Im here to help :)

**Comment by fat-tire** [comment]
Thanks for the offer...  the best way to assist is to grab the code and just start hacking at it.  You can look at the issues queue to see the types of things people are asking for and just start contributing!

For now I'm going to close this PR (it's not mergeable as is anyway, and i think we're a ways to go from being M-ready...) but definitely thank you and keep the contributions coming!

**Pull request closed without merging**
