### PR TITLE
Fixing msf (developp soft)

### PR DESCRIPTION
**Pull request by DeveloppSoft**
Some gem package can't be installed, so just add some lines like me to force installation of them  (I have  already do that and it work).
Please note that it is better to compile the last ruby version for android.
DeveloppSoft.

### CODE REVIEW

**Comment by Pukson** [comment]
So it will now work? Only need to compile it?

**Comment by Pukson** [comment]
Got this error while running in android studio

http://i.imgur.com/XoLO7F6.png

**Comment by DeveloppSoft** [comment]
Sorry, I forgot something (the "")

**Comment by DeveloppSoft** [comment]
Just see my new pull request

**Pull request closed without merging**
