### PR TITLE
Lol

### PR DESCRIPTION
**Pull request by JaCk1052**
Good

### CODE REVIEW

**Comment by wan7teen-ping** [comment]
sir how i cant permission copy this csploit..and how i cant run csploit to my termux after i download app csploit

**Comment by xaitax** [comment]
You can fork it w/out any issues.

**Comment by wan7teen-ping** [comment]
sir cant i run csploit to phone not root

Pada Ahd, 9 Ogo 2020, 8:50 PM xaitax <notifications@github.com> menulis:

**Comment by ole-h** [comment]
what

**Pull request closed without merging**
