### PR TITLE
Minor changes...

### PR DESCRIPTION
**Pull request by fat-tire**
Fixed a potential crasher and changed some strings.

### CODE REVIEW

**Comment by itxx00** [comment]
+1

**Comment by apkmadhax** [comment]
+1 your ass. I got an email over that

**Comment by fat-tire** [comment]
Hey @tux-mind I added a few new commits to update the build...  doesn't seem to break anything.

Also notice in this commit some crash fixes from a couple months ago.  cheers, ft

**Comment by gainan** [comment]
Hi @fat-tire ,
regarding this fix https://github.com/fat-tire/android-1/commit/8c03dffee4a9385d2bd7f80022846adc0e39a8a4, I´ve taken a look at it by casuality and I've realized that the real problem is that the ToolBox() class is instantiated prior to mSettingReceivers = new LinkedList<SettingReceiver>();
https://github.com/fat-tire/android-1/blob/8c03dffee4a9385d2bd7f80022846adc0e39a8a4/cSploit/src/org/csploit/android/core/System.java#L124
https://github.com/fat-tire/android-1/blob/8c03dffee4a9385d2bd7f80022846adc0e39a8a4/cSploit/src/org/csploit/android/core/System.java#L146

When ToolBox() is initialized, also the class Ruby() is instantiated, and it makes a callback to System.registerSettingsListener() which is still not initialized, firing the null exception.

Maybe besides this fix, could you move the line 124 to 147?, in other words, initialize ToolBox() after mSettingsReceivers. what do you think? I've tested it and seems to work fine.

regards.

**Comment by fat-tire** [comment]
I tried it and it seems on first look anyway to have fixed better than my band-aid. :)  Give me one sec and I'll include that.  I've also updated build.gradle to use the newest SDK 23.

**Comment by fat-tire** [comment]
Okay, added.  If everyone tries this and it seems to work... let me know because I think i can merge all this to the main branch.... assuming that's cool with @tux-mind and it seems to work for everyone.

**Comment by fat-tire** [comment]
Figured I'd get rid of those deprecated apache dependencies as well.  @gainan and @tux-mind  let me know what you think.

Another one-liner fix I didn't push is this:
```
diff --git a/cSploit/src/org/csploit/android/events/Hop.java b/cSploit/src/org/csploit/android/events/Hop.java
index 0101ded..c3d4a6e 100644
--- a/cSploit/src/org/csploit/android/events/Hop.java
+++ b/cSploit/src/org/csploit/android/events/Hop.java
@@ -5,7 +5,7 @@ import java.net.InetAddress;
 /**
  * an hop has been found
  */
-public class Hop {
+public class Hop implements Event {
   public final int hop;
   public final long usec;
   public final InetAddress node;
```

This seems to fix a crasher w/traceroute (nmap), though it seems that some hops are being skipped.  Still it's not crashing.

Also, I mentioned in [another PR](https://github.com/cSploit/android/pull/245#issuecomment-141255452) that IRC might be a good place to discuss various things I'm noticing.  If you (or I guess anyone else reading this) is interested, I'm in #csploit on freenode.  ([link](http://webchat.freenode.net/?channels=%23csploit))

**Comment by tux-mind** [comment]
I'll give it a look ASAP, thanks <3

I think that I already fix the toolbox issue in the develop branch.

Anyway we have to organize the cSploit team, including you @fat-tire,
anyone that want to collaborate should be able to find what are the TODOs
and where start looking for learning certain parts of the app.

Thanks you all for your efforts and sorry for spending too less time for
this project.
I hope to find some free time in this week end.

**Comment by fat-tire** [comment]
Okay so @tux-mind now there are conflicts w/master w/this commit.  I haven't looked at what they are yet, but I'm sure not that big a deal.  The biggest benefit i think you'll get from the PR is the update to all the SDK stuff/build tools/etc.  But there are some fixes as well and some strings are changed for clarity...

Anyway, just to clarify process.

1.  I can resolve them but not until Wed probably.  Then I can merge it myself.
2.  You could resolve/merge this PR before then
3.  None of the above
4.  Something else (merge into the develop branch?  Merge into a new branch? )

Also, feel free to stop by IRC to discuss this or whatever else.  gainan and others have been dropping by.  Cheers!

(PS-- I want to add to others-- I got something like 20 emails today related to cSploit, many of which were people saying basically nothing constructive..  Remember that when you leave a comment, every single person who's watching the repo by default gets an email sent to them with your message.  Contributions to the discussion are great, but the same bug reports again and again or the "I have nothing to say" emails are starting to get annoying...  I don't want to be Mr. Grumpy here, because everyone's input is welcome, but just sayin'.  Thanks in advance, everyone!)

**Comment by gainan** [comment]
> I got something like 20 emails today related to cSploit, many of which were people saying basically nothing constructive.. Remember that when you leave a comment, every single person who's watching the repo by default gets an email sent to them with your message.

That's why I proposed to have another place to talk about cSploit topics not related with bugs/PRs/suggestions. I'm new over here so I won't insist much on that ;)

Regarding your fix @fat-tire https://github.com/fat-tire/android-1/commit/12ba46a6b478fdeba0c561e7eaccfdad15beddd5, as far as I can tell it's not merged yet on the develop branch.

**Comment by tux-mind** [comment]
Toolbox issue were fixed in c06609566b943ded212007fa7602bc91075f820c

merging pull request...

I'll open an issue soon about the spam and where to talk about non-development related stuff.

**Comment by tux-mind** [comment]
merged with 7bdcf8451776838a45d1b1ba5319212d7d115217

@fat-tire can you explain me why some gradle function should return true ?
thanks in advance for sharing your knowledge with us :blush:

**Comment by fat-tire** [comment]
Heya @tux-mind --  I returned true on those gradle functions because Android Studio's LINT was telling me that a value was expected :)  Simple as that.... thanks!

**Pull request closed without merging**
