### PR TITLE
some dSploit->cSploit changes.  Affects not much.

### PR DESCRIPTION
**Pull request by fat-tire**
I mean, might as well, right?

### CODE REVIEW

**Comment by fat-tire** [comment]
I added a snackbar commit there too.  Probably should have done it on another branch.  Oh well.  Feel free to accept one and not the other or what-have-you.

**Comment by tux-mind** [comment]
is the snackbar working on android API 9 ?

thanks for your awesome work @fat-tire :blush:

**Comment by fat-tire** [comment]
I'm pretty sure the snackbar should work in api 9.  From the [instructions](https://developer.android.com/tools/support-library/index.html):

> your applications can use the libraries' features and still be compatible with devices running Android 1.6 (API level 4) and up.

Anyone have an old gingerbread device laying around who wants to give it a shot?

Also note that the snackbar is drawn at the root view (android.R.id.content) of the activity (or the given context really), so unlike a toast it won't show up system-wide or on other activities.. ...At least I don't think it will.  This was just a very fast 10 minute late-Saturday night addition- I didn't even add the colors like in the notifications, which could be supported too, so if anyone wants to build on it, feel free.

**Comment by tux-mind** [comment]
I personally prefer the toast because you get notified of the connection even if you are in a different app.

I think that snackbar should be used for notification about an action performed in this moment, in that view/context.

**Pull request merged**
