### PR TITLE
Bring cSploit code up to date (Android Pie/AS 3.3 current) + AndroidX + other fixes

### PR DESCRIPTION
**Pull request by fat-tire**
Just brought the build up to date and tested on an older Android 6.01 device, which seems to still work.  That's not to say there aren't going to be problems-- but my cursory tests didn't find them.  Was able to do a portscan and MITM of a test rasppi on the local network, and that's about all I tested.  Themes and stuff still works on the device I tested, and the appcompat/androidx support should be more complete.

This should hopefully fix the #941 permissions issue as well, though someone else will have to confirm this on newer Android.

If no one has any complaints, I'll probably just accept this commit in a few days or so into the `develop` branch..  If you do have complaints, please submit a proposed solution if possible.

Cheers!

### CODE REVIEW

**Comment by fat-tire** [comment]
(@xaitax heads up if you can do a test build it would be appreciated.)

**Comment by xaitax** [comment]
No problem. Once you commit it will be automatically built.

**Comment by kimocoder** [comment]
@fat-tire It's just sad this project isn't active.. cause it's a hell of an app (or was).
will do some test builds to check the latest, as the officials aren't updated since 10 june of 2016

**Comment by fat-tire** [comment]
@kimocoder Cool  If you build it without issue and it looks like it works I'll accept the changes to the devel branch and I guess the nightly builds will include it...  Thx.

**Comment by xaitax** [comment]
I will build it once it's committed for everyone to test. ;)

**Comment by kimocoder** [comment]
I'm getting a multidex error. Attached image to inspect
error

**Comment by fat-tire** [comment]
Q:  Are you using AS 3.3 latest alpha/canary + latest gradle test?

**Comment by kimocoder** [comment]
Yes. AS 3.3 Canary 6

**Comment by fat-tire** [comment]
Hmm....  From [this](https://stackoverflow.com/questions/42969220/getting-package-android-support-multidex-does-not-exist-after-upgrading-to-and) it appears a solution may be to add to `build.gradle`:

      implementation 'com.android.support:multidex:1.0.1'

Strangely I don't need it.  But tell me if it fixes anything and if so I'll add it.

Update:  Actually the issue is with the AndroidX version not being available rather than the old multidex....  Is it possible you haven't updated your library support in Android Studio to the latest?

**Comment by kimocoder** [comment]
I'm running on a clean AS 3.3 Canary 6. Do I need any packages installed? If yes, well.. which to be specific?
Everything in my clean setup is updated..

**Comment by fat-tire** [comment]
I've just updated this to include multidex.  You should use the latest canary 7 I think.  In the SDK Manager, you want to have the latest build tools and libraries and stuff up to date

Can you try building this latest version and let me know if it builds for you?

**Comment by kimocoder** [comment]
It gets further, but gives me this error..
error

**Comment by fat-tire** [comment]
Hmm it shouldn't be using v4.app.anything now that it's using jetpack, which replaced the support library stuff.  Can you try clearing the app's cache  (it's in one of the menus) and the build files and restarting AS completely, and if that doesn't work take a look at [this](https://stackoverflow.com/questions/49837344/program-type-already-present-android-support-v4-app-backstackrecord) as something there may help?  it's strange because using AS canary, I don't have this (or the other multidex issue)...

**Comment by kimocoder** [comment]
I got the solution..  added this and now it compiles the APK
img_20180824_191614

Switched from Windows to Linux AS also gave me less troubles.
There are still some compile warnings that needs to be fixed though

**Comment by fat-tire** [comment]
As a (simpler) alternative solution, what happens if you remove mavencentral() completely in all four places, ie:

```
diff --git a/build.gradle b/build.gradle
index d736044f..e0c93946 100644
--- a/build.gradle
+++ b/build.gradle
@@ -3,7 +3,6 @@ buildscript {
     repositories {
         google()
         jcenter()
-        mavenCentral()
     }
     dependencies {
         classpath 'com.android.tools.build:gradle:3.3.0-alpha07'
@@ -14,6 +13,5 @@ allprojects {
     repositories {
         google()
         jcenter()
-        mavenCentral()
     }
 }
diff --git a/cSploit/build.gradle b/cSploit/build.gradle
index 0a566821..141692c7 100644
--- a/cSploit/build.gradle
+++ b/cSploit/build.gradle
@@ -2,7 +2,6 @@ buildscript {
     repositories {
         google()
         jcenter()
-        mavenCentral()
     }
     dependencies {
         classpath 'com.android.tools.build:gradle:3.3.0-alpha07'
@@ -13,7 +12,6 @@ allprojects {
     repositories {
         google()
         jcenter()
-        mavenCentral()
     }
 }
 apply plugin:  'com.android.application'
```

When I try it it builds fine.  If you can report it works, I'll push it and then merge to `develop` branch.  Be sure to clear the project/cache.  Thanks.

**Comment by kimocoder** [comment]
Then I'll get back to the error 
"Program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy"


org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':cSploit:transformClassesWithMultidexlistForDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
	at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: com.android.build.api.transform.TransformException: Error while generating the main dex list.
	at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
	... 34 more
Caused by: com.android.build.api.transform.TransformException: Error while generating the main dex list.
	at com.android.build.gradle.internal.transforms.D8MainDexListTransform.transform(D8MainDexListTransform.kt:143)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	... 51 more
Caused by: com.android.builder.multidex.D8MainDexList$MainDexListException: com.android.tools.r8.errors.CompilationError: Program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy
	at com.android.builder.multidex.D8MainDexList.generate(D8MainDexList.java:87)
	at com.android.build.gradle.internal.transforms.D8MainDexListTransform.transform(D8MainDexListTransform.kt:128)
	... 54 more
Caused by: com.android.tools.r8.errors.CompilationError: Program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy
	at com.android.tools.r8.utils.ProgramClassCollection.resolveClassConflictImpl(ProgramClassCollection.java:64)
	at com.android.tools.r8.utils.ProgramClassCollection.lambda$create$0(ProgramClassCollection.java:25)
	at java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:1990)
	at com.android.tools.r8.utils.ProgramClassCollection.create(ProgramClassCollection.java:24)
	at com.android.tools.r8.graph.LazyLoadedDexApplication$Builder.build(LazyLoadedDexApplication.java:124)
	at com.android.tools.r8.dex.ApplicationReader.read(ApplicationReader.java:123)
	at com.android.tools.r8.dex.ApplicationReader.read(ApplicationReader.java:86)
	at com.android.tools.r8.GenerateMainDexList.run(GenerateMainDexList.java:41)
	at com.android.tools.r8.GenerateMainDexList.run(GenerateMainDexList.java:111)
	at com.android.builder.multidex.D8MainDexList.generate(D8MainDexList.java:83)
	... 55 more

**Comment by kimocoder** [comment]
Then I'll get back to the error
"Program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy"

Syncing fine, but building APK fails

screenshot from 2018-08-25 12-51-58

And remember.. I run a clean Android Studio - Canary 7 with all build-tools and SDK updated.

**Comment by fat-tire** [comment]
That's so strange. So the solution for you is to add that maven url line?  Putting that back lets it build?

**Comment by kimocoder** [comment]
Wow.. really don't know whats happening over here. Tried to replay the build from yesterday, which was successfull.. but noe I only get the above issue with the exact same maven url lines I used yesterday. Better you do this without me, it may be my low experience on AS that's causing the troubles, but this is a bit weird anyways

**Comment by fat-tire** [comment]
Alrighty, thanks @kimocoder for giving it a shot-- as it's been a few days and it #worksforme I'll commit to `develop` and we can fix any issues if they arise.  Heads up to @xaitax that this does need the latest build environment...

**Comment by xaitax** [comment]
Can't build unfortunately. Downloaded a fresh SDK and installed:

> root@rootbitch:/opt/android-sdk-linux/tools/bin# ./sdkmanager --list
Installed packages:=====================] 100% Computing updates...             
  Path                               | Version | Description                    | Location                           
  -------                            | ------- | -------                        | -------                            
  build-tools;28.0.2                 | 28.0.2  | Android SDK Build-Tools 28.0.2 | build-tools/28.0.2/                
  extras;google;google_play_services | 49      | Google Play services           | extras/google/google_play_services/
  extras;google;m2repository         | 58      | Google Repository              | extras/google/m2repository/        
  patcher;v4                         | 1       | SDK Patch Applier v4           | patcher/v4/                        
  platform-tools                     | 28.0.0  | Android SDK Platform-Tools     | platform-tools/                    
  platforms;android-28               | 6       | Android SDK Platform 28        | platforms/android-28/              
  tools                              | 26.1.1  | Android SDK Tools 26.1.1       | tools/     

Anything missing?

**Comment by xaitax** [comment]
`./gradlew assembleRelease`

Task :cSploit:transformClassesWithMultidexlistForRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cSploit:transformClassesWithMultidexlistForRelease'.
com.android.build.api.transform.TransformException: Error while generating the main dex list.

**Comment by fat-tire** [comment]
It's kind of hard to tell from that list as it's missing C/Rs but [here is my installed list... ](https://gist.github.com/fat-tire/c1ee79f35c830e8def920f5635789191).

When I do ./gradlew assembleRelease it builds for a while and ends with

BUILD SUCCESSFUL in 57s...


Can you build a debug build?  Also, could you paste the build log somewhere?  You have updated the SDK?

**Comment by xaitax** [comment]
You have basically everything installed, huh? ;)

I posted the assembleDebug Log here: https://paste2.org/GKdMVCVw

SDK is latest from today - got a fresh one and then installed the above shown packages. In the meantime I will go through your list and see what might make sense to install as well.

**Comment by kimocoder** [comment]
From my point of view, there is something with the "support library" that's off

**Comment by xaitax** [comment]
Here is the whole debug.log

http://rootbitch.cc/csploit.txt

**Comment by fat-tire** [comment]
Hmm.  A few observations:

*  javax.tools.ToolProvider isn't found, which msgpack needs.  Should be in java as far back as 1.6 tho.  You are building with Java 1.8 yes?

*  "com.android.internal.util.Predicate" not found.  I see this was deprecated in api 26... should use  java.util.function.Predicate in instead.

The support library is completely switched from the old style to the androidx [jetpack](https://developer.android.com/jetpack/) stuff.  Dunno if anything special needs to be downloaded to support that.

Per [this](https://stackoverflow.com/questions/37906750/getting-error-execution-failed-for-task-apptransformclasseswithmultidexlistfor), can you try with --stacktrace to get more detail?  The only errors I see are some translated strings that don't appear in the default string xml.

**Comment by fat-tire** [comment]
(also-- yeah i pretty much include everything.  Or rather, over time they've all eventually been installed...)

**Comment by xaitax** [comment]
Yeah, building it with JDK 1.8.

Output with stacktrace here:
https://paste2.org/8FFnyAcD

**Comment by fat-tire** [comment]
Do you guys have the following in `gradle.properties`?
```
android.enableJetifier=true
android.useAndroidX=true`
```
If not please add these two lines to `gradle.properties` in the root directory of the source code (ie, `android/`) and give it a try...

Thx!

**Comment by kimocoder** [comment]
There is lots of information of the build issue around the Google, just don't have time to look into it for a week or so..
https://github.com/material-components/material-components-android/issues/110

**Comment by fat-tire** [comment]
Yeah I think adding those lines to gradle.properties will fix this.  @xaitax can you confirm?

**Comment by xaitax** [comment]
It built. Can you try the nightly please? 
There were also some issues with the latest NDK from where I will commit the changes to Application.mk / Android.mk if it works.

Also please not only run it but also test if some of the tools still work. Do not have a rooted phone here.

**Comment by kimocoder** [comment]
I got the Nexus 6P and I may confirm there are several issue.. May disclose them after work this evening

**Comment by fat-tire** [comment]
Awesome @xaitax!   @kimocoder please do post any issues you find.  I am probably going to update the gradle dist (4.10 is out now) as well as add those two lines to gradle.properties in the next day or so... though feel free to do so if I don't get to it soon.

**Comment by fat-tire** [comment]
Done!  #969

**Comment by kimocoder** [comment]
@fat-tire there is an issue running this.. at startup, this happens before force closing

Android v7.1.1
Device: Nexus 6P (angler)

screenshot_20180828-214128

**Comment by kimocoder** [comment]
Nevermind, got it working by using the nightly build instead

**Comment by fat-tire** [comment]
Awesome.  @xaitax if you have issues let me know otherwise we should be up-to-date now as far as the app itself goes.  (libraries & dled bits not quite.. @tux-mind would need to update that stuff)

**Comment by pahapoika** [comment]
Nice to see @fat-tire keeping us alive :D
I honestly have no idea whats the progress with the cSploit 2.0, but it seems like tux-mind is still extremely busy.

**Pull request merged**
