### PR TITLE
Msf

### PR DESCRIPTION
**Pull request by DeveloppSoft**
Correcting another error.
Please forgive me but I can't test source codes, forme the moment, so, tanks to Pukson who send me all the errors.

### CODE REVIEW

**Comment by Pukson** [comment]
If i change the msgpack to bundleInstallTask it will work, but the app then wont start on my phone..

**Comment by DeveloppSoft** [comment]
OK, lets forget that solution, I have another one, the csploit's ruby is
the ruby version of 1995, so they must change it

**Comment by Pukson** [comment]
Sure, so what to do next?

**Comment by DeveloppSoft** [comment]
Lets, compile a new version.

**Comment by Pukson** [comment]
How long till i can test again?

**Comment by DeveloppSoft** [comment]
Wait 10-15 min.

**Comment by DeveloppSoft** [comment]
Sorry Pukson, I failed.
I wrote an issue to port ruby since there is no explanation on how to do
this, so I am waiting.
But, for the solution of forcing gems installation, it doesn't work, so,
here, I failed.

**Comment by DeveloppSoft** [comment]
Thanks for your help.

**Comment by DeveloppSoft** [comment]
please see my issue for another try

**Pull request closed without merging**
