### PR TITLE
Fixed a few minor things.

### PR DESCRIPTION
**Pull request by Avamander**

### CODE REVIEW

**Comment by fabinhojcr** [comment]
@Avamander Nothing has changed, only tiny to uppercase

**Comment by Avamander** [comment]
Settings look horrible with the one lowercase item and it must be fixed. I made the thing more consistent and the pull request get's closed?

**Comment by fat-tire** [comment]
I agree-- these seem like legit grammar/presentation fixes-- what's the problem with them?

**Comment by fabinhojcr** [comment]
Ok, I found that really gets better

**Comment by tux-mind** [comment]
@fabinhojcr thanks for your help :blush: 

next time ensure to merge into the develop branch :grin: 

let me fixing this.

**Comment by fabinhojcr** [comment]
@tux-mind Okay, next time remember that ☺

**Pull request merged**
