### PR TITLE
Updated czech translation

### PR DESCRIPTION
**Pull request by Tajnymag**
I hope that I fixed it now :-)

### CODE REVIEW

**Comment by tux-mind** [comment]
perfect, let me merge it by hand to produce only 1 commit ( 7 commits to change 3 lines a bit confusing :confounded: )

**Comment by tux-mind** [comment]
merge in 06cc477

thanks :heart:

**Comment by Tajnymag** [comment]
I'm sorry for this commit mess. I'm just learning how to use Github and don't know any other way how to quickly sync my fork with the upstream :-(

**Comment by tux-mind** [comment]
No worries, curiosity is the best thing the humankind have.
learning with pleasure :wink:

**Pull request closed without merging**
