### PR TITLE
Added new magic numbers

### PR DESCRIPTION
**Pull request by nullpointer17**
Added new magic numbers from my list.

### CODE REVIEW

**Comment by Rubenoo** [comment]
@nullpointer17 would you mind explaining what this pull request does/changes?

**Comment by pahapoika** [comment]
@Rubenoo agreed with Rubenoo.

**Comment by nullpointer17** [comment]
It adds some more numbers to crack Alice Wifi Passwords.

**Comment by pahapoika** [comment]
And Alexa is??

**Comment by nullpointer17** [comment]
Alice you mean? They are routers from an italian provider. The algorithm to generate default passwords on these routers needs, in addition to the algorithm, some numbers calculated from real routers... I saw on cSploit there already is a list of these numbers and i had some more... so I entered them... if it's not useful/wanted you can just ignore me :)
Here is the old algorithm disclosure (but it's in italian): https://wifiresearchers.wordpress.com/2010/06/02/alice-agpf-lalgoritmo/

**Comment by pahapoika** [comment]
@nullpointer17 
Oh. Thanks for explaining.

Commits doesnt have impact to core functions/doesnt remove anything so merging

**Pull request merged**
