### PR TITLE
Fun multi-pack of commits

### PR DESCRIPTION
**Pull request by fat-tire**
Eventually will want to do complex animations, but for now, I think
the dissolves make it feel more like a single program rather than
multiple activities sliding in and out.  Makes me less dizzy too.

Also animate listview items.

*NOTE:  this was originally in the show_portcount branch but was redone for the current develop branch.*

### CODE REVIEW

**Comment by fat-tire** [comment]
Note-- I took way too long to squash the otherwise confusing as hell portscan count branch into a single commit-- and it's included in this PR.  I also had to make some changes to bring it up to date with the develop branch.  Note there are some issues:

*  Added hosts don't get scanned automatically
*  If you do scan them manually, the count only appears when you slide them away and back (probably needs an invalidate on the listview)
*  routers aren't scanned (but can be manually as well)

to this I'll add a feature request--

* make a setting to not scan automatically (this probably could use some more discussion because maybe the network shouldn't be scanned at all automatically, let alone the ports)

**Comment by fat-tire** [comment]
Okay I messed with trying to fix #373 -- a "new browser" -- basically the URL bar asked for plus a progress meter, improved pinch-to-zoom, and some compatibility fixes.

Enjoy.

**Comment by tux-mind** [comment]
will work solving known bugs if I can get write access to the repo :wink: 

thanks for all your big efforts @fat-tire

**Comment by fat-tire** [comment]
@tux-mind done.

**Comment by Rubenoo** [comment]
It workes nice, well done fattire but those are the bugs i found on it: a bug related to #387 logcat : https://gist.github.com/Rubenoo/6ad953b8072f4da48d06.

**Comment by tux-mind** [comment]
@fat-tire I think that the bug reported from @Rubenoo is the following:
in the ActionActivity when you scroll down, a new element come into the visible list ( MITM ), it has the new animation, making it invisible for a sec.

all other bugs about port scanning should be fixed, I've tested on my home network ( 2 hosts, 1 gw ).
I think that the changes can impact performance on big network, it will be great if someone can test this PR on network with more than 100 hosts.

I didn't tested the hijacker webview.

the port box it's cool @fat-tire , great job :blush:

**Comment by fat-tire** [comment]
Hmm.. is that the issue, @Rubenoo?   The animation when an item pops in should take less than like 1/10th of a second.  It's just a quick fade-in instead of a (harsher) pop-in.  Shouldn't really be a dramatic performance difference...

I had to make a minor change to get the above to be merge-able, but should I just do it?  We can make any adjustments/additions in develop... (?)

**Comment by fat-tire** [comment]
Two more additions to the PR--  a fix to the strings to make capitalization fit Google's design standards as well as a new preference to avoid the new auto-portscan if you don't want it.

@tux-mind --- I think we should commit this sooner rather than later.  If it's good with you, @tux-mind , feel free to merge, or I can do it.  If problems show up we can fix it as a new PR.. but right now there are 16 commits in here, one of which is a squash of like 5 other commits, so I think we should get it in to avoid it diverging from other changes too much.

Plus as I'm using it, it looks pretty cool.  Really nice work, TM.

**Pull request merged**
